# Generated by Django 5.2.8 on 2025-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Optional Facebook live/stream URL for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Optional poster or flyer image for this event.', null=True, upload_to='events/posters/'),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube live/stream URL for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_url',
            field=models.URLField(blank=True, help_text='Optional Zoom meeting/webinar URL for this event.'),
        ),
    ]
