# Generated by Django 5.2.8 on 2025-12-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortyDaysNoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
            ],
            options={
                'verbose_name': '40 Days Note Category',
                'verbose_name_plural': '40 Days Note Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FortyDaysNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Name/title of the insight or note', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('banner_image', models.ImageField(help_text='Banner picture for this note', upload_to='fortydays/notes/banners/')),
                ('content', models.TextField(help_text='Notes or key takeaways from the session')),
                ('expert_name', models.CharField(blank=True, help_text='Name of the expert/speaker who shared this insight', max_length=200)),
                ('session_date', models.DateField(blank=True, help_text='Date of the evening session (optional)', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this note from public view')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this note on the main page')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(help_text='Category for organizing this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='resources.fortydaysnotecategory')),
            ],
            options={
                'verbose_name': '40 Days Note',
                'verbose_name_plural': '40 Days Notes',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
