# Generated by Django 5.2.8 on 2025-11-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('scripture_reference', models.CharField(blank=True, max_length=255)),
                ('passage_text', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('reflection', models.TextField(blank=True)),
                ('prayer', models.TextField(blank=True)),
                ('action_point', models.TextField(blank=True)),
                ('publish_date', models.DateField(db_index=True)),
                ('is_published', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='devotions/audio/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='devotions/pdf/')),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devotions', to='devotions.devotionseries')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
