# Generated by Django 5.2.8 on 2025-12-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='quote',
            field=models.TextField(blank=True, help_text='Inspirational quote'),
        ),
        migrations.AddField(
            model_name='devotion',
            name='theme',
            field=models.CharField(blank=True, help_text="Monthly theme (e.g., 'Theme for April: Memorials')", max_length=200),
        ),
        migrations.AddField(
            model_name='devotion',
            name='topic',
            field=models.CharField(blank=True, help_text="Daily topic (e.g., 'Blessings with a Charge')", max_length=250),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='action_point',
            field=models.TextField(blank=True, help_text='Action point or practical application'),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='body',
            field=models.TextField(help_text='Devotional Message - main content'),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='passage_text',
            field=models.TextField(blank=True, help_text='Scripture passage text'),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='prayer',
            field=models.TextField(blank=True, help_text="Today's Prayer"),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='reflection',
            field=models.TextField(blank=True, help_text='Reflection questions or points'),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='scripture_reference',
            field=models.CharField(blank=True, help_text='Foundation Text (NKJV)', max_length=255),
        ),
    ]
