# Generated by Django 5.2.8 on 2025-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0002_devotion_quote_devotion_theme_devotion_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for this devotion', null=True, upload_to='devotions/images/'),
        ),
    ]
