# Generated by Django 5.2.8 on 2025-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0003_devotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionseries',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for this series (used on series pages and filtered lists)', null=True, upload_to='devotions/series_banners/'),
        ),
    ]
