# Generated by Django 5.2.8 on 2025-11-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('receive_daily_devotion', models.BooleanField(default=True)),
                ('receive_special_programs', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('email', 'phone', 'channel')},
            },
        ),
    ]
