# Generated by Django 5.2.8 on 2025-12-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0004_devotionseries_banner_image'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title/Subject of the notification', max_length=200)),
                ('custom_message', models.TextField(blank=True, help_text='Optional: Custom message to include. If devotion is set, this will be added to the devotion content.')),
                ('scheduled_date', models.DateField(help_text='Date to send the notification')),
                ('scheduled_time', models.TimeField(help_text='Time to send the notification')),
                ('is_paused', models.BooleanField(default=False, help_text='Pause this notification from being sent')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paused', 'Paused'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was actually sent', null=True)),
                ('send_to_email', models.BooleanField(default=True, help_text='Send to email subscribers')),
                ('send_to_whatsapp', models.BooleanField(default=True, help_text='Send to WhatsApp subscribers')),
                ('only_daily_devotion_subscribers', models.BooleanField(default=True, help_text='Only send to subscribers who opted in for daily devotions')),
                ('email_sent_count', models.IntegerField(default=0, help_text='Number of emails sent')),
                ('email_failed_count', models.IntegerField(default=0, help_text='Number of emails that failed')),
                ('sms_sent_count', models.IntegerField(default=0, help_text='Number of SMS/WhatsApp sent')),
                ('sms_failed_count', models.IntegerField(default=0, help_text='Number of SMS/WhatsApp that failed')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this notification')),
                ('devotion', models.ForeignKey(blank=True, help_text="Optional: Link to a specific devotion. If not set, will use today's devotion.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='devotions.devotion')),
            ],
            options={
                'verbose_name': 'Scheduled Notification',
                'verbose_name_plural': 'Scheduled Notifications',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
    ]
