# Generated by Django 5.2.8 on 2025-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_schedulednotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotification',
            name='send_to_sms',
            field=models.BooleanField(default=True, help_text='Send to SMS subscribers'),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='whatsapp_failed_count',
            field=models.IntegerField(default=0, help_text='Number of WhatsApp messages that failed'),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='whatsapp_sent_count',
            field=models.IntegerField(default=0, help_text='Number of WhatsApp messages sent'),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='sms_failed_count',
            field=models.IntegerField(default=0, help_text='Number of SMS that failed'),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='sms_sent_count',
            field=models.IntegerField(default=0, help_text='Number of SMS sent'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
