"""
Django settings for uplift_afrika project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-g5np!uqm*2c5@85bsgs3xj)4v@(9%d2l)(f9@c5gtmoy$jmfz=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# Check if we're running a management command early (before INSTALLED_APPS)
# This helps optimize app loading
IS_MANAGEMENT_CMD_EARLY = len(sys.argv) > 1 and sys.argv[1] not in ['runserver', 'collectstatic', 'shell_plus']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'django_countries',
    # Local apps
    'apps.core',
    'apps.pages',
    'apps.devotions',
    'apps.resources',
    'apps.events',
    'apps.community',
    'apps.subscriptions',
    'apps.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Temporarily disable WhiteNoise in development to speed up startup
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Temporarily disabled - enable after running migrations
    # 'apps.pages.middleware.AnalyticsMiddleware',  # Track page views for analytics
]

ROOT_URLCONF = 'uplift_afrika.urls'

# Optimize template loading for management commands
# Keep required context processors for Django admin, but skip directory scanning
if IS_MANAGEMENT_CMD_EARLY:
    # Skip template directory scanning during management commands
    # But keep required context processors for Django admin
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],  # Empty during management commands - no file scanning
            'APP_DIRS': False,  # Disable app directory scanning - major speedup
            'OPTIONS': {
                'context_processors': [
                    # Keep required ones for Django admin
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
                # Disable debug during management commands
                'debug': False,
            },
        },
    ]
else:
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

WSGI_APPLICATION = 'uplift_afrika.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Development: Use SQLite (no setup required)
# Production: Switch to PostgreSQL or MySQL
USE_POSTGRESQL = config('USE_POSTGRESQL', default=False, cast=bool)

if USE_POSTGRESQL:
    # PostgreSQL configuration for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='uplift_afrika'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    # SQLite configuration for development (default)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Use the early check for consistency
IS_MANAGEMENT_CMD = IS_MANAGEMENT_CMD_EARLY

# Disable password validators during management commands to speed up startup
# They're not needed for makemigrations, migrate, etc.
if IS_MANAGEMENT_CMD:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lome'  # Timezone for UPLIFT Afrika

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Aggressively optimize static files scanning for management commands
# Completely disable file scanning during makemigrations, migrate, etc.
SKIP_STATIC_SCAN = any(cmd in sys.argv for cmd in ['makemigrations', 'migrate', 'shell', 'dbshell', 'test', 'check'])

# For runserver, we need static files but can optimize the scanning
IS_RUNSERVER = 'runserver' in sys.argv

# Use the early check for consistency (already defined above)
# IS_MANAGEMENT_CMD is already set from IS_MANAGEMENT_CMD_EARLY

# Completely disable static file operations during management commands
if SKIP_STATIC_SCAN or IS_MANAGEMENT_CMD_EARLY:
    # Empty directories and finders to prevent ANY file scanning
    STATICFILES_DIRS = []
    STATICFILES_FINDERS = []  # Disable all finders - no file scanning at all
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
elif not SKIP_STATIC_SCAN:
    # Only scan when actually needed (runserver, collectstatic)
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]
    
    # In development with runserver, use a faster static files storage
    if DEBUG and IS_RUNSERVER:
        STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
        # Include AppDirectoriesFinder so admin (and other app) static files are found and served
        STATICFILES_FINDERS = [
            'django.contrib.staticfiles.finders.FileSystemFinder',
            'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        ]
    else:
        # Default finders for collectstatic
        STATICFILES_FINDERS = [
            'django.contrib.staticfiles.finders.FileSystemFinder',
            'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        ]

# Template optimization is already handled above during TEMPLATES definition
# No need to modify it here

# WhiteNoise configuration for efficient static file serving
# Disable in development for faster startup - only enable in production after collectstatic
# Don't set STATICFILES_STORAGE in DEBUG mode to avoid slow startup
if not DEBUG:
    # Only use in production after running collectstatic
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# In DEBUG mode, Django will use default storage (faster for development)

# Media files (user uploads)
# Skip media file operations during management commands
if not IS_MANAGEMENT_CMD_EARLY:
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # Minimal config during management commands
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'  # Still set but won't be accessed

# Caching configuration for better performance
# Use LocMemCache for both development and production to support analytics rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Analytics settings
ENABLE_ANALYTICS = config('ENABLE_ANALYTICS', default=True, cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Paystack configuration (keys stored in environment variables)
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')

# Django REST Framework settings
# Only load full REST framework settings if not running management commands
# This speeds up makemigrations, migrate, etc.
if not IS_MANAGEMENT_CMD:
    REST_FRAMEWORK = {
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
        'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 20,
    }
else:
    # Minimal REST framework config for management commands
    REST_FRAMEWORK = {}

# Email configuration (for counseling booking notifications)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@upliftyourmorning.com')

# FastR SMS API configuration (for SMS notifications)
FASTR_API_KEY = config('FASTR_API_KEY', default='')  # Secret key
FASTR_API_PUBLIC_KEY = config('FASTR_API_PUBLIC_KEY', default='DJbhctlognNbQuEhPMTB9A')  # Public key
FASTR_API_BASE_URL = config('FASTR_API_BASE_URL', default='https://prompt.pywe.org/api/client')
FASTR_SENDER_ID = config('FASTR_SENDER_ID', default='COME CENTRE')

# Twilio WhatsApp API configuration (for WhatsApp notifications)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')  # Twilio sandbox number or your WhatsApp Business number

# Google Calendar configuration
GOOGLE_CALENDAR_ENABLED = config('GOOGLE_CALENDAR_ENABLED', default=False, cast=bool)
GOOGLE_CALENDAR_EMAIL = config('GOOGLE_CALENDAR_EMAIL', default='godswilltk@gmail.com')

# Attendance Analytics Access Code
# Set this in your .env file: ATTENDANCE_ANALYTICS_CODE=your-secret-code
# If not set, defaults to 'uplift2024' (change this to something more secure)
ATTENDANCE_ANALYTICS_CODE = config('ATTENDANCE_ANALYTICS_CODE', default='uplift2024')
