# Generated by Django 5.2.8 on 2025-12-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortyDaysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Start date of the 40 Days event (e.g., November 10, 2025)')),
                ('end_date', models.DateField(help_text='End date of the 40 Days event (e.g., December 19, 2025)')),
                ('morning_youtube_url', models.URLField(blank=True, help_text='YouTube live URL for morning sessions (5:00-5:30am Ghana time)')),
                ('morning_facebook_url', models.URLField(blank=True, help_text='Facebook live URL for morning sessions (5:00-5:30am Ghana time)')),
                ('evening_youtube_url', models.URLField(blank=True, help_text='YouTube live URL for evening sessions (6:00-7:00pm Ghana time)')),
                ('evening_facebook_url', models.URLField(blank=True, help_text='Facebook live URL for evening sessions (6:00-7:00pm Ghana time)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to disable this configuration (useful for past years)')),
            ],
            options={
                'verbose_name': '40 Days Configuration',
                'verbose_name_plural': '40 Days Configurations',
                'ordering': ['-start_date'],
            },
        ),
    ]
