# Generated by Django 5.2.8 on 2025-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_fortydaysconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortydaysconfig',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner/flyer image for the 40 Days section on the homepage', null=True, upload_to='fortydays/banners/'),
        ),
    ]
