# Generated by Django 5.2.8 on 2025-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('preferred_date', models.DateField(help_text='Preferred date for counseling session')),
                ('preferred_time', models.TimeField(help_text='Preferred time for counseling session')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Session duration in minutes')),
                ('topic', models.CharField(blank=True, help_text='Brief topic or reason for counseling', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Additional message or details')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, help_text='Admin-approved date', null=True)),
                ('approved_time', models.TimeField(blank=True, help_text='Admin-approved time', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID after creation', max_length=255)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Counseling Booking',
                'verbose_name_plural': 'Counseling Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
