# Generated by Django 5.2.8 on 2025-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_counselingbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
