# Generated by Django 5.2.8 on 2025-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_counselingbooking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text='The URL path that was visited (e.g., /devotions/, /events/)', max_length=500)),
                ('page_name', models.CharField(blank=True, help_text="Human-readable page name (e.g., 'Home', 'Devotions List')", max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the visitor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('referer', models.URLField(blank=True, help_text='The page the user came from (if available)')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pages_pagev_created_a1d2f6_idx'), models.Index(fields=['path'], name='pages_pagev_path_ba7dda_idx')],
            },
        ),
    ]
