# Generated by Django 5.2.8 on 2026-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Full name of the person making the pledge', max_length=200)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional, in international format e.g., +233 20 123 4567)', max_length=50)),
                ('country', models.CharField(blank=True, help_text='Country of residence (optional, ISO 3166-1 alpha-2 code)', max_length=2)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp')], default='email', help_text='Preferred method of contact', max_length=20)),
                ('contact_info', models.CharField(blank=True, help_text='Additional contact information (e.g., WhatsApp number if different from phone, preferred time to call, etc.)', max_length=200)),
                ('pledge_type', models.CharField(blank=True, choices=[('monetary', 'Monetary (Money)'), ('non_monetary', 'Non-Monetary (Services, Goods, Time, etc.)')], default='monetary', help_text='Type of pledge: monetary or non-monetary', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount pledged (required for monetary pledges)', max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, choices=[('GHS', 'GHS - Ghana Cedis'), ('USD', 'USD - US Dollars'), ('GBP', 'GBP - British Pounds'), ('EUR', 'EUR - Euros'), ('NGN', 'NGN - Nigerian Naira'), ('ZAR', 'ZAR - South African Rand'), ('OTHER', 'Other Currency')], default='GHS', help_text='Currency of the pledge amount (required for monetary pledges)', max_length=10)),
                ('other_currency', models.CharField(blank=True, help_text="Specify currency if 'Other' is selected", max_length=50)),
                ('donation_frequency', models.CharField(blank=True, choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('annually', 'Annually (Once per year)'), ('custom', 'Custom (Specify below)')], default='one_time', help_text='How often would you like to donate?', max_length=20)),
                ('custom_frequency', models.CharField(blank=True, help_text="Specify custom donation frequency (e.g., 'Every 6 months', 'Bi-weekly', etc.)", max_length=200)),
                ('non_monetary_description', models.TextField(blank=True, help_text="Describe what you're pledging (services, goods, time, skills, etc.) - required for non-monetary pledges")),
                ('redemption_date', models.DateField(blank=True, help_text='When do you plan to redeem/fulfill this pledge? (optional)', null=True)),
                ('redemption_timeframe', models.CharField(blank=True, help_text="Alternative: Specify a timeframe for redemption (e.g., 'Within 3 months', 'Q2 2025', etc.)", max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information or notes from the pledger')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the pledge', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes about this pledge')),
                ('completed_date', models.DateField(blank=True, help_text='Date when the pledge was fulfilled/completed', null=True)),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='counselingbooking',
            name='duration_minutes',
            field=models.IntegerField(default=30, help_text='Session duration in minutes (fixed at 30 minutes)'),
        ),
    ]
