# Generated by Django 5.2.8 on 2026-01-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pledge_alter_counselingbooking_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD (automatically calculated)', max_digits=15, null=True),
        ),
    ]
