# Generated by Django 5.2.8 on 2026-01-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_pledge_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='conversion_date',
            field=models.DateField(blank=True, help_text='Date when the conversion rate was fetched', null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used for conversion (from currency to USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='conversion_source',
            field=models.CharField(blank=True, help_text='Source of the exchange rate (e.g., exchangerate-api.com, ECB)', max_length=50),
        ),
    ]
