# Generated by Django 5.2.8 on 2026-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pledge_conversion_date_pledge_conversion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date for this attendance record (one record per day)', unique=True)),
                ('youtube_views', models.IntegerField(default=0, help_text='Total views on YouTube for this day')),
                ('youtube_likes', models.IntegerField(blank=True, default=0, help_text='Number of likes on YouTube (optional)')),
                ('youtube_comments', models.IntegerField(blank=True, default=0, help_text='Number of comments on YouTube (optional)')),
                ('facebook_views', models.IntegerField(default=0, help_text='Total views on Facebook for this day')),
                ('facebook_reactions', models.IntegerField(blank=True, default=0, help_text='Number of reactions on Facebook (optional)')),
                ('facebook_comments', models.IntegerField(blank=True, default=0, help_text='Number of comments on Facebook (optional)')),
                ('facebook_shares', models.IntegerField(blank=True, default=0, help_text='Number of shares on Facebook (optional)')),
                ('notes', models.TextField(blank=True, help_text="Any additional notes about this day's attendance")),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='pages_atten_date_a7de68_idx')],
            },
        ),
    ]
