# Generated by Django 5.2.8 on 2026-01-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_add_question_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('student', 'UPLIFT Student Movement (Campus Coordinator)'), ('professional', 'UPLIFT Professional Forum (Professional Coordinator)')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('campus_or_profession', models.CharField(help_text='Campus name (Student Movement) or profession/field (Professional Forum)', max_length=255)),
                ('profile_message', models.TextField(help_text='Short professional profile / why you want to serve as coordinator')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Coordinator Application',
                'verbose_name_plural': 'Coordinator Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
