# Generated by Django 5.2.8 on 2026-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_add_coordinator_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorapplication',
            name='additional_professional_info',
            field=models.TextField(blank=True, help_text='Industry, key skills, career highlights, or anything else relevant to your professional profile'),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='additional_student_info',
            field=models.TextField(blank=True, help_text='Leadership experience, interests, expected graduation, or anything else relevant as a student'),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='campus_name',
            field=models.CharField(blank=True, help_text='Name of campus / institution', max_length=255),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='country',
            field=models.CharField(blank=True, help_text='Country of residence', max_length=200),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile (optional)'),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='Employer or organisation name', max_length=255),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='program_of_study',
            field=models.CharField(blank=True, help_text='Program or course of study', max_length=255),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='role_or_profession',
            field=models.CharField(blank=True, help_text='Job title or profession', max_length=255),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='e.g. Year 2, Final year', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinatorapplication',
            name='years_experience',
            field=models.CharField(blank=True, help_text='e.g. 5 years, 10+', max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinatorapplication',
            name='campus_or_profession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coordinatorapplication',
            name='profile_message',
            field=models.TextField(help_text='Why you want to serve as coordinator and what you hope to contribute'),
        ),
    ]
