# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_coordinator_student_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='uplift_morning_facebook_url',
            field=models.URLField(blank=True, help_text='Facebook live URL for Uplift Your Morning (5:00–5:30 AM). Shown every morning during the live window.'),
        ),
    ]
