# Generated by Django 5.2.8 on 2025-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='is_public',
            field=models.BooleanField(default=True, help_text="User's preference to make testimony public to encourage community members"),
        ),
    ]
